version: '3'
name: "storage"
services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:latest
    network_mode: bridge
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ~/development/redis/data:/data
      - /etc/localtime:/etc/localtime
    ports:
      - "6379:6379"

  mysql:
    hostname: mysql
    image: mysql:latest
    container_name: mysql
    network_mode: bridge
    volumes:
      - ~/development/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    restart: unless-stopped

  postgres:
    hostname: postgres
    image: postgres:14
    container_name: postgres
    network_mode: bridge
    volumes:
      - ~/development/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5555:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    network_mode: bridge
    environment:
      PGADMIN_DEFAULT_EMAIL: hypofiasco@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rootroot
      PGADMIN_LISTEN_PORT: 80
    volumes:
      -  ~/development/postgresql/pgadmin:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
    ports:
      - "5050:80"
    restart: unless-stopped
    # host: host.docker.internal    # pgadmin connection configuration